apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-hello-route
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nodejs-hello.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nodejs-hello
              servicePort: 3000